version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /opt/flask-mongodb-boilerplate:/counter_app
    links:
      - db:mongodb
    container_name: counterappmongodb_web_1
    depends_on:
      - db
    environment:
        PORT: 5000
        SECRET_KEY: 'you-will-never-guess'
        MONGODB_HOST: mongodb
        MONGODB_DB: counter
  db:
    image: mongo:3.4.4
    container_name: counterappmongodb_db_1
